name: Gemini CLI - Current Time

on:
  issue_comment:
    types: [created]

jobs:
  gemini-cli:
    if: |
      github.event.issue.pull_request &&
      (
        contains(github.event.comment.body, '@gemini-cli') ||
        contains(github.event.comment.body, '@gemini')
      ) &&
      (
        github.event.comment.author_association == 'OWNER' ||
        github.event.comment.author_association == 'MEMBER' ||
        github.event.comment.author_association == 'COLLABORATOR'
      )
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      pull-requests: write
      issues: write
    steps:
      - name: Generate GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Get PR Branch
        id: get-pr-branch
        run: |
          PR_URL="${{ github.event.issue.pull_request.url }}"
          PR_NUMBER=$(basename "$PR_URL")
          BRANCH_NAME=$(gh pr view "$PR_NUMBER" --json headRefName -q '.headRefName' --repo ${{ github.repository }})
          echo "branch=$BRANCH_NAME" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}

      - uses: actions/checkout@v4
        with:
          ref: ${{ steps.get-pr-branch.outputs.branch }}
          token: ${{ steps.app-token.outputs.token }}

      - name: Get PR Number
        id: get-pr-number
        run: |
          PR_URL="${{ github.event.issue.pull_request.url }}"
          echo "pr_number=$(basename "$PR_URL")" >> $GITHUB_OUTPUT

      - name: Gemini CLI Action
        uses: google-gemini/gemini-cli-action@main
        with:
          github_token: ${{ steps.app-token.outputs.token }}
          gcp_project_id: ${{ secrets.GCP_PROJECT_ID }}
          gcp_region: ${{ secrets.GCP_REGION }}
          gcp_workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          gcp_service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          gemini_api_key: ${{ secrets.GEMINI_API_KEY }}
          repository: ${{ github.repository }}
          pr_number: ${{ steps.get-pr-number.outputs.pr_number }}
          user_request: "what is the current time"
          settings_json: |
            {
              "github": {
                "allowed_commands": [
                  "date",
                  "gh"
                ]
              },
              "telemetry": {
                "gcp": {
                  "enabled": true
                }
              },
              "sandbox": {
                "enabled": false
              }
            }
